### ISSUE TITLE
LeaveTimeUsageBuilder Spec

### ISSUE THREAD

**Issue by Maxwell-Alexius** [5xRuby/daikichi#107]
Refer to issue #99

**Comment by Eileen0917** [comment]
1. LeaveTimeUsageBuilder 應通過：
- [ ] 額度全包休假期間
- [ ] 休假開始日或結束日等於某額度開始日或截止日
- [ ] 休假跨越假日


2. LeaveTimeUsageBuilder 不應通過：
- [ ] 休假期間中某天沒有被任何額度包含到
- [ ] 休假期間中的某天額度不足

**Comment by Eileen0917** [comment]
於 PR #157 中完成，故關閉此 issue。
