### ISSUE TITLE
當假單要被新增時，可以創建出leave_time_usages，若不行則假單新增失敗

### ISSUE THREAD

**Issue by Maxwell-Alexius** [5xRuby/daikichi#108]

**Comment by Maxwell-Alexius** [comment]
備註：當新增假單失敗時，藉由 leave_hours_by_date 印出缺漏的時數表

**Comment by Maxwell-Alexius** [comment]
@YushengLi  @Eileen0917  這個是不是可以進入 closed 狀態? 因為 PR #110 已經 merge 進去而且審核沒問題

**Comment by Eileen0917** [comment]
在 PR #110 中完成且測試無誤。
