### ISSUE TITLE
補班之休假時數計算

### ISSUE THREAD

**Issue by YushengLi** [5xRuby/daikichi#131]
目前休假時數之計算是填入起始、結束時間之後，再由 `Biz` 計算出共休了多少工時，`Biz` 當中可透過設定 `holidays` 的方式來將休假排除於計算之中。

但是由於 `Biz` 當中無法額外設定連續假期前後在週六補班的少數狀況，目前在週六補班請假的狀況會出現無法正確計算時數的問題。

為了暫時排除這個狀況，打算先採用 `Biz` 原作者於[官方 Repo 的 Issue #5](https://github.com/zendesk/biz/issues/5) 中提出的方法，先將週六設定為 Working Period，再將非補班的週六設定為 `holidays` 來讓時數可以正常計算。

**Comment by Eileen0917** [comment]
於 PR #134 中完成，故關閉此 issue。
