### ISSUE TITLE
每一次使用到 LeaveTime 補額度時，需檢查 leave_hours_by_date 補齊的狀態

### ISSUE THREAD

**Issue by Maxwell-Alexius** [5xRuby/daikichi#132]
[Bug] 當如果同時有很多個  LeaveTime 可以被使用，但是實際上只有 2 個 LeaveTime 補足 leave_hours_by_date -> LeaveTimeUsage 產生的資料中，有 used_hours 為零的狀態

**Comment by YushengLi** [comment]
@Eileen0917 這個應該已經在 ef7188f 當中修掉了，請再確認一下 😄

**Comment by Eileen0917** [comment]
於 PR #133 中修正，故關閉此 issue。
