### ISSUE TITLE
審核假單頁面選擇年份時會出錯

### ISSUE THREAD

**Issue by Eileen0917** [5xRuby/daikichi#137]
審核假單頁面選擇年份後會跳出錯誤。

**Comment by YushengLi** [comment]
這個出錯的原因應該是 JavaScript Event Binding 到同一個 #ID，所以選擇後會試圖 Turbolinks.visit 請假狀況月統計頁面，可是又缺乏 month key 造成的錯誤。

**Comment by Eileen0917** [comment]
於 PR #150 中修正顯示、排序、搜尋方式，解決此問題，故關閉此 issue。
