### ISSUE TITLE
補上 User .auto_assign_leave_time callback spec

### ISSUE THREAD

**Issue by Maxwell-Alexius** [5xRuby/daikichi#152]

**Comment by Eileen0917** [comment]
新增 manager、hr、employee 員工時有"病假、事假、在家上班、特休"
新增 parttime 員工時有"病假、事假、在家上班"
其餘都沒有

**Comment by Eileen0917** [comment]
全薪病假：56 / 1年
半薪病假：184 / 1年
事假：112 / 1年
年假：依年資
在家上班：16 / 1個月

**Comment by Eileen0917** [comment]
於 PR #164 中完成，故關閉此 issue。
