### ISSUE TITLE
leave_hours_by_dates 無法正常計算

### ISSUE THREAD

**Issue by Eileen0917** [5xRuby/daikichi#166]
目前 leave_hours_by_dates 無法正常計算，
故顯示不出任何 leave_applications 的 leave_hours_by_dates。

**Comment by YushengLi** [comment]
這邊上週討論過，是因為同時註冊了一般的 Callback 及 Observer的關係，由於 LeaveApplication Callback 有點複雜，請統一移至 Observer 管理。

這邊如果 @Eileen0917 可以直接搬完，可以先發一個 PR。

**Comment by Maxwell-Alexius** [comment]
@Eileen0917 這個issue由我來接手，有空可以幫我寫一下 #29 spec 大概要測試的項目，因為我已經大致上把 #29 要求的內容完成了，只差寫測試

**Comment by Eileen0917** [comment]
於 PR #168 中完成，並測試無誤，故關閉此 issue。
