### ISSUE TITLE
新增假單時，不明原因 500 Error

### ISSUE THREAD

**Issue by zetavg** [5xRuby/daikichi#211]
不知道 DevOps 的 issue 是不是開在這邊 XD

發生時間 2017-07-31 下午 12:58:51

![2017-07-31 12 58 51](https://user-images.githubusercontent.com/3784687/28763388-35cbf072-7583-11e7-9144-ad258d2cfd60.png)

**Comment by lctseng** [comment]
8/1號下午四點半左右我也遇到+1

**Comment by pastleo** [comment]
你們申請的是病假嗎？ @zetavg @lctseng 

我 6/30 嘗試申請病假也是直接變成這個畫面

**Comment by lctseng** [comment]
我是用事假，一天的

**Comment by ryudoawaru** [comment]
已解決，是 deploy 問題
