### ISSUE TITLE
忘記密碼功能無法使用

### ISSUE THREAD

**Issue by spartchou** [5xRuby/daikichi#219]
忘記密碼了 @@" 但該功能似乎還不能使用？ 按下`Send me reset password instructions`會出現 `We're sorry, but something went wrong.` 的錯誤頁面

**Comment by Eileen0917** [comment]
如果有忘記密碼的話可能先我，幫你們重設一組密碼，這個我會再找時間修～

**Comment by Eileen0917** [comment]
修改 application.yml 中的 devise > mailer_sender 後已修復功能
