### ISSUE TITLE
remote 請假條件更改為一週一天

### ISSUE THREAD

**Issue by Eileen0917** [5xRuby/daikichi#223]
須在前一天的 19:00 前提出申請，並限制一週一天（一個月共四天）

**Comment by telsaiori** [comment]
其實我在想這個要直接系統上限制嗎？
我在想會不會有任何狀況就是會允許有人7點以後或是一週超過1天之類的....(雖然可能沒有）
因為感覺不管怎樣,可不可以remote還是需要人工去判斷,比方說一天不在辦公室的人太多或是專案上的問題之類的

**Comment by telsaiori** [comment]
https://www.flowdock.com/app/5xruby/hrsystem/threads/Ofa3bkwiKmsfu1Ip3t8LSM643d2
先保持原樣ＸＤ

**Comment by telsaiori** [comment]
先做限制一週一天
如果真的有任何例外就管理員幫忙送申請

**Comment by Eileen0917** [comment]
finished in #273
