### ISSUE TITLE
查看歷年假單頁面, 應該預設列出最後幾筆資料

### ISSUE THREAD

**Issue by treekey999** [5xRuby/daikichi#230]
> https://daikichi.5xruby.tw/leave_applications

1. filter 介面的狀態, 應該加個 all , 不能只有特定選項能選

2. 通常都是請完假之後, 就只想確認審核有沒有過, 應該一頁無腦 f5 就可以看得到資訊比較方便

**Comment by Eileen0917** [comment]
於 PR #250 中完成，故關閉此 issue。
