### ISSUE TITLE
請假結果 email

### ISSUE THREAD

**Issue by treekey999** [5xRuby/daikichi#235]
目前有請假申請的話, 會寄信通知 hi@5xruby.tw

1. 可以再做一個 "請假結果" 通知信, 寄信給 請假的人, 會更完善

2. 信件內容可以多加一點資訊, 例如假別、時間等等

**Comment by Eileen0917** [comment]
1. 目前 i18n 跑掉
2. staging 送出測試信

**Comment by Eileen0917** [comment]
取消也要寄信通知管管

**Comment by Eileen0917** [comment]
於 PR #236 #238 #251 中完成，故關閉此 issue。
