### ISSUE TITLE
需可查詢「某月份需要扣薪水的名單和時數」

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#239]
目前的每月休假時數查詢是總表，但算薪水需要知道有無扣薪狀況（以及要扣多少時數）

**Comment by telsaiori** [comment]
目前的員工休假統計頁面已經可以符合要求,只差
1.把需要扣新的項目highlight起來(事假&半薪病假）
但是現在半薪病假顯示的資料是錯的,要先修正

**Comment by Eileen0917** [comment]
於 PR #244 中完成，故關閉此 issue。
