### ISSUE TITLE
leave time 計算方式修改

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#25]
討論中

**Comment by jodeci** [comment]
新規則：以 2015/4/1 到職為例

2015年度，基礎年假 7 天，以 n/365 比例調整
2016年度，新年度重新清算年假，因 1/1 未滿一年，故仍為 7 天，但 4/1 服務滿一年，在 4/1 後再多加一天為 8 天（新增的第八天需在服務滿一年後才能使用）
2017 年度，新年度重新清算年假，因服務已滿一年，之後就正常的 n++ 為 9 天

**Comment by YushengLi** [comment]
因為 2017 年勞基法修正年假計算方式，公司規定跟著修正計價方式，所以這邊的規則 Deprecated 了。
