### ISSUE TITLE
日期格式請統一為 yyyy-mm-dd

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#252]
「yyyy年mm月dd日」看的好累 -_-

**Comment by telsaiori** [comment]
@jodeci 
請問一下是哪個部分,因為目前日期應該都是有統一成年月日,差別只在後面會加上是星期幾
![f87508f7-8051-4adc-be25-6e36b601808a](https://user-images.githubusercontent.com/14009154/34090116-a42c5806-e3ef-11e7-9c96-82e9f03e4545.png)

**Comment by jodeci** [comment]
你截圖的地方就是了啊 XD
「2017年12月04日」v.s.「2017-12-04」

**Comment by telsaiori** [comment]
我打完才發現我會錯意了ww
那還需要顯示星期幾嗎

**Comment by jodeci** [comment]
先保留吧

**Comment by Eileen0917** [comment]
於 PR #254 中完成，故關閉此 issue。
