### ISSUE TITLE
remote額度改成一週一天

### ISSUE THREAD

**Issue by telsaiori** [5xRuby/daikichi#257]
現在是一個月給四天,但是有可能發生和我一樣的悲劇

> 在我剛剛想要申請remote的時候發現,我12月已經把額度用完了
因為一個月只會生4天,可是12月有五個禮拜,雖然第一個禮拜只有12月1號&2號
但是我12/1號用了一次
然後接下來每個禮拜也都用了一次
所以我第五個禮拜也就是下禮拜沒額度了

**Comment by Eileen0917** [comment]
同 #223，故關閉此 issue。
