### ISSUE TITLE
需要有「約聘人員」的請假紀錄

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#259]
公司有月薪制的約聘人員，請假只需要事先報備即可（aka 不受公司管理 / 不需主管審核），但每月算薪水仍需要扣除請假天數，需要有紀錄

**Comment by telsaiori** [comment]
aka是什麼？

**Comment by jodeci** [comment]
also know as .......

**Comment by telsaiori** [comment]
約聘人員是不管為了什麼理由請假都會扣薪水嗎？

**Comment by jodeci** [comment]
是唷

**Comment by telsaiori** [comment]
我確定一下
我們約聘人員現在應該是沒有神社的帳號？
所以是要下面哪一種方式
1. Sabrina幫他們上系統登記
2.讓他們有帳號自己登記

**Comment by jodeci** [comment]
目前的確是沒有帳號，然後因為其實他們也不受 sabrina 管理，讓他們自己登記比較好？

**Comment by telsaiori** [comment]
- 約聘人員只需要事假
- 他們不需要額度這個概念
所以我現在想的有
1. 約聘人員建假單的時候skip某些callback(create_leave_time_usages之類的..)
2. 建完假單狀態就設成approve

然後和其他人不同,反正只要有時數就要扣薪,所以他的時數可以從leave_application&leave_hours_by_dates就算出來
所以要的話我想把約聘人員的統計頁面和現有的員工休假統計分開
因為會從不同table去算時數
（其他人的時數之後是想要做成可以直接從leave_time_usage去撈資料來算)

**Comment by Eileen0917** [comment]
PR #266
