### ISSUE TITLE
新增公傷病假與生理假

### ISSUE THREAD

**Issue by sabrina823** [5xRuby/daikichi#268]
像同事於上下班出車禍，因為是上下班時間，屬於應申請公傷病假，但因公司目前並未有這個假別可申請，考量未來同事若有較嚴重情況，需較多天數住院或休養時，申請上可能會有點疑慮，所以討論是否新增此假別。

一般傷病假：有額度限制，會扣半薪(五倍優於勞基法，有七天全薪額度，需檢附證明)
公傷病假：公傷病假沒有額度上限，以不扣薪為原則 (須檢附證明，若需長時間休養，需請醫生開立相關診斷證明) 
@jodeci @kaochenlong @ryudoawaru

**Comment by Eileen0917** [comment]
生理假 
一個月 8 小時 兩天內請完
一年六天，第七天後扣半薪

公傷病假
如公喪婚產之特殊架

**Comment by Eileen0917** [comment]
PR #271
