### ISSUE TITLE
[todo] 非 fulltime 正職員工的計假方式

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#27]
大原則：
- 有值班才有休假
- 「請假」動作還是需要在系統上發生

待決：
quota 計算方式

**Comment by jodeci** [comment]
確認：

- 新增 role (命名..)
- 此類型員工特休時數為 0，其餘相同

**Comment by YushengLi** [comment]
@Eileen0917 這個功能應該是在 LeaveTimeBuilder Service 當中完成了，麻煩確認功能是否完成並更新狀態，如果不知道要怎麼確認的話請再問我。

**Comment by Eileen0917** [comment]
新增 parttime 員工時只有"病假、事假、在家上班"
確認此 issue 和 issue #29 同時於 PR #90 中完成
