### ISSUE TITLE
[refactor] user role 命名調整

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#28]
admin: 應該不需要了，seed 也不用預先建了？
pending: 改成由 manager/hr 新增帳戶的話應該也不需要了？

manager: 主管
hr: 人資
employee: 全職員工
parttime: 兼職員工
-----以上歸為 internal ------
intern: 實習生
contractor: 外包
-----以上歸為 external ------
resigned: 離職

**Comment by YushengLi** [comment]
@Eileen0917 麻煩確認狀態

**Comment by Eileen0917** [comment]
user role是否有需要留著pending?

**Comment by YushengLi** [comment]
@Eileen0917 這個 Issue 應該可以關掉了？
