### ISSUE TITLE
需要可以初始化新員工的休假時數

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#29]

**Comment by Eileen0917** [comment]
新增員工自到職日起一年內，年假、病假、事假，及當月 Remote 的額度。

**Comment by Eileen0917** [comment]
新增 manager、hr、employee 員工時有"病假、事假、在家上班、特休"
確認此 issue 和 issue #27 同時於 PR #90 中完成

**Comment by Eileen0917** [comment]
bug : 

- [ ] 非操作新增員工當日的到職者 初始化額度期限不對

**Comment by Eileen0917** [comment]
今天新增員工：

1. 今天後 ( 含今天 ) 到職
例：2017/04/18 到職
長出以年計算的額度為 `2017/04/18 - 2018/04/17`

2. 今天前 ( 不含今天，一年內 ) 到職
例：2017/04/17 到職
長出以年計算的額度為 `2017/04/17 - 2018/04/16`

3. 一年以前到職
例：2013/11/05 到職
長出以年計算的額度為 `2016/11/05 - 2017/11/04`

註：
2. 3. 情況中，若遇到額度更新的過渡期，須將今年與明年的額度一起長出。
例：2013/04/30 到職，2017/04/18 登記新增員工
則需長出以年計算的額度 `2016/04/30 - 2017/04/29` 與 `2017/04/30 - 2018/04/29` 兩筆額度

**Comment by Eileen0917** [comment]
目前僅以 新增日與到職日相同 或 新增日早於到職日 之新增員工可長出初始化休假額度，
也就是 1. 今天新增員工為今天後 ( 含今天 ) 到職 此類別。
其餘需手動增加休假額度。

**Comment by Eileen0917** [comment]
在表單中新增兩個欄位：
1. 是否自動生成額度
2. 要從哪個時間點開始計算額度

之後會依照到職日長出所有額度，包含過期的。

**Comment by Eileen0917** [comment]
新增的病假額度為"病假 240小時"，但應該要新增的額度為"全薪病假 56小時" + "半薪病假 184小時"

**Comment by Eileen0917** [comment]
@Maxwell-Alexius 
測試內容：
填入到職日期可正確長出額度。

例：填寫 2013/11/05 到職
長出以年計算的額度為 `2013/11/05 - 2014/11/04` + `2014/11/05 - 2015/11/04` + `2015/11/05 - 2016/11/04` + `2016/11/05 - 2017/11/04`

**Comment by Eileen0917** [comment]
需判斷 "起算日期" 是否在 "到職日期" 的一年內。
且 LeaveTimeButchBuilder 調整為不判斷第一年的使用者。

**Comment by Eileen0917** [comment]
於 PR #167 中完成，故關閉此 issue。
