### ISSUE TITLE
沒有依照正常順序扣休假額度

### ISSUE THREAD

**Issue by Chiahuii** [5xRuby/daikichi#308]
部分同事請事假，神社沒有依照正常順序扣假（補休—> 特休 —> 事假）
目前遇到此狀況的有 ok, 佳蕙, Fred

**Comment by ryudoawaru** [comment]
請給我操作步驟附截圖，在這邊

**Comment by Chiahuii** [comment]
因篇幅較長，說明和截圖附在 HackMD。

https://hackmd.io/v1vGmK58T7yqHH8tI_b36g?view
