### ISSUE TITLE
[todo] 預先請跨年度的特休

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#31]
情境：2016/12/01 請 2017/02/01 的假

- annual leave 允許從現在年度的 quota 先請隔年的假
- 只允許超支隔年的假，如果是要在同年度內請特休但時數不夠，多出的時數要算事假
- 其他假種不可以跨年度請
- 超支時，需要警示 user
- 超支的假單上需要做「顯著標示」，以提醒主管
- 每年重新 init quota 時要把去年超支的部分從今年的 annual quota 扣除

**Comment by YushengLi** [comment]
# 預請跨年度特休方式 討論紀錄 Dec. 22nd, 2016

- 每年度 10/1 先初始化隔年休假，隔年休假初始化後始得請隔年度休假
  - 其他假種不得跨年度請
  - 如此不會再有超支問題，若請假超出現有額度，直接 Reject。

**Comment by YushengLi** [comment]
剛檢查的時候突然想到，目前扣除 `LeaveTime` quota 的策略是直接使用 `start_time.year` 去找尋對應的 `LeaveTime`，然後從該筆 LeaveTime 上面扣除額度。

這會導致如果要請 `12/31 - 1/2` 的假這樣的情形下，需要人工拆兩張假單處理。

**Comment by YushengLi** [comment]
現在所有的 LeaveTime 額度起算基礎是按照到職日為基礎計算，不會有跨年度請休的問題。
