### ISSUE TITLE
已被 approve 的假單，只能在休假實際發生前取消並藉由 LeaveTimeUsage 返回 LeaveTime 之 usable_hours

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#32]
情境：在 10/1 請了 10/20 的假並已被 approve

- 只能在 10/1~20 之間取消假單

**Comment by Maxwell-Alexius** [comment]
備註：
1. 前端時使用 `LeaveAppication.may_cancel?` 方法來確認需不需要 render 前端的取消按鈕
2.  LeaveTime 的 Model Spec

**Comment by Eileen0917** [comment]
於 PR #121 中完成，且測試無誤，故關閉此 issue。
