### ISSUE TITLE
[todo] notification

### ISSUE THREAD

**Issue by jodeci** [5xRuby/daikichi#35]
假單送出後需要通知主管審核
... approve/reject 好像也應該通知苦主？

通知方式
- flowdock bot（最佳）
- slack bot（次之）
- email（劣）

**Comment by lctseng** [comment]
我記得通知用的modules好像在cfp系統用過XD
(支援slack與email)
可以考慮把同樣的code搬過去用

**Comment by elct9620** [comment]
https://www.flowdock.com/api/messages

Flowdowck 應該可以用這個 API 相容 Slack 改 XD

**Comment by jodeci** [comment]
flowdock 官方 gem 用的都是 deprecated 的 api （遠目）

**Comment by ryudoawaru** [comment]
有最新的在 Shopmatic 那個 channel 有用，詳情請問 Marsz

**Comment by Eileen0917** [comment]
於 PR #172 中完成 Flowdock 的通知，但是以 Push API (deprecated) 完成，故先不關閉此 issue。

**Comment by Eileen0917** [comment]
於 PR #182 中完成，故關閉此 issue。
