### ISSUE TITLE
First Year Employee 計假方式遇到閏年會有一天的差異

### ISSUE THREAD

**Issue by YushengLi** [5xRuby/daikichi#48]
## 狀況
- 新進員工初始化假期額度時，若「加入年份為閏年」、「加入日期大於 2/28」，則會造成計算時比「非閏年」多出一天的假期。
- 相關的 Code Snippets
```ruby
def first_year_rate
  (days_by_leave_type * first_year_adjustment).round * DAILY_HOURS
end

def first_year_adjustment
  (DAYS_IN_YEAR - user.join_date.yday) / DAYS_IN_YEAR
end
# 此處 DAYS_IN_YEAR 常數設定為 365 日
```
- 出錯的 Spec：`LeaveTimeSpec#init_quota/sick leave/first year employee should have 136 hours`
```ruby
context "sick leave" do
  it "first year employee should have 136 hours" do
    sick = FactoryGirl.create(:leave_time, :sick, user: first_year_employee)
    sick.init_quota
    expect(sick.quota).to eq 136     
  end
end

# `first_year_employee` 此處設定為 June 1st 到職之員工
```

## Example
- 同樣於 June 1st 到職之員工：
  - 2016 (閏年) 到職之員工，有 17 天 (136 小時) 休假
  - 2017 (平年) 到職之員工，有 18 天 (144 小時) 休假

## 問題
- 這個問題是要動態調整 Spec 還是要調整休假的計算方式？

**Comment by beersheep** [comment]
這個現在改成第一年也給 30 天，所以應該可以 close 了？

**Comment by YushengLi** [comment]
看起來應該是不會遇到這個問題了，感謝提醒！
