### ISSUE TITLE
除了基本四大假別外，要對其他勞基法所規定假別做對應處理

### ISSUE THREAD

**Issue by YushengLi** [5xRuby/daikichi#51]
- [勞動基準法相關假別](http://www.mol.gov.tw/topic/3067/14530/19538/)

Requested by @sabrina823

**Comment by YushengLi** [comment]
目前系統打算設定的休假假別為
### 依到職日設定的休假
- 年假
- 事假
- 病假

### 每月重新計算休假
- 遠端休假

### 獎勵休假
- 補休

### 特殊休假
- 公假
- 婚假
- 產假
- 喪假

婚假、產假、喪假為特殊事件發生時，提出相關文件由老闆給予，所以這部分採取類似補休的方式，由老闆手動開啟休假額度。

公假屬於老闆直接批准的休假，沒有額度問題，考慮不受 LeaveTime 綁定限制？(與 #67 邏輯衝突)

@sabrina823 這邊有哪個休假類別被漏掉的嗎？

**Comment by jodeci** [comment]
remote 不是休假，是要上班的，放在這邊不大對？

**Comment by YushengLi** [comment]
因為其實申請 Remote 及休假的邏輯是相同的，所以當初想說就放在申請 LeaveApplication 的地方，如果不適合的話可以再搬走？

**Comment by jodeci** [comment]
邏輯相同可以拆出來共用，但「請假」和「申請 remote」是兩件事。
非要放在一起不可的話，至少不能叫「遠端休假」，**它不是休假**，是「遠端工作」。

**Comment by YushengLi** [comment]
阿，原來是我打錯字了，抱歉剛剛一邊在跟很多人講話恍神沒注意到就弄錯了，是遠端工作沒錯。
這邊的確應該是分開來比較清楚。

**Comment by Eileen0917** [comment]
於 PR #176 #180 中完成，故關閉此 issue。
