### ISSUE TITLE
出現隨機 Test Fail

### ISSUE THREAD

**Issue by beersheep** [5xRuby/daikichi#60]
Error Log:

    1) LeaveTime init_quota bonus leave initial bonus leave time is 0
     Failure/Error: let(:senior_employee) { FactoryGirl.create(:user, :employee, join_date: 30.years.ago) }

     ActiveRecord::RecordInvalid:
       校驗失敗: 帳號 已經被使用
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:78:in `raise_validation_error'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:50:in `save!'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `block in save!'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `save!'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:45:in `save!'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/configuration.rb:18:in `block in initialize'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/evaluation.rb:15:in `create'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/strategy/create.rb:9:in `tap'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/factory.rb:42:in `run'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/factory_runner.rb:28:in `run'
     # /Users/RoyHuang/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/models/leave_time_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./spec/models/leave_time_spec.rb:319:in `block (4 levels) in <top (required)>'

    Finished in 6.85 seconds (files took 7.04 seconds to load)
    122 examples, 1 failure
    Failed examples:
    rspec ./spec/models/leave_time_spec.rb:318 # LeaveTime init_quota bonus leave initial bonus leave time is 0

**Comment by YushengLi** [comment]
這個應該是因為 `DatabaseRewinder` 未被正確設定導致，目前不再遇到此問題。
