### ISSUE TITLE
將新增假單之假別更改為額度

### ISSUE THREAD

**Issue by Eileen0917** [5xRuby/daikichi#75]
以額度做為請假的選擇
- 病假
- 事假
- 年假
- 補休+到期日` 到期日不同視同不同額度休假，都要使用時要送出不同假單`
- 公假 `第一次申請需附證明`
- 婚假 `第一次申請需附證明`
- 喪假 `第一次申請需附證明`
- 產假 `第一次申請需附證明`
(以下為上面有申請過了才會出現的選項)
- 公假+到期日
- 婚假+到期日
- 喪假+到期日
- 產假+到期日

**Comment by Maxwell-Alexius** [comment]
註記：先處理前面四個假別

**Comment by Eileen0917** [comment]
因為issue #82 成立
所以不需要依額度選擇假別
關閉此issue
