### ISSUE TITLE
Settingslogic - application_leave_type in application.yml should redesign its data structure

### ISSUE THREAD

**Issue by Maxwell-Alexius** [5xRuby/daikichi#76]

**Comment by YushengLi** [comment]
會將這些 Deprecated 方法移除，並將依賴這些 Deprecated 方法的功能重寫或是移除。

**Comment by YushengLi** [comment]
@Eileen0917 Completed in PR #101 
@Maxwell-Alexius Please rebase your current working branch with latest update on development to make sure these changes won't affect features you are currently working on.
