### ISSUE TITLE
LeaveApplication#Cancel Should Return Locked Hours to LeaveTime via LeaveTimeUsage

### ISSUE THREAD

**Issue by Maxwell-Alexius** [5xRuby/daikichi#77]
Destroying leave application has no error, however,  "cancelling" leave application **still deduct the leave time usable hours**

**Comment by Maxwell-Alexius** [comment]
- Rspec broken
- leave time duration should be in unit of hours

**Comment by Maxwell-Alexius** [comment]
由於 #99 修改假單結構產生 LeaveTimeUsage，故此issue 需改為 當假單被刪除時，必須 return 回
 locked_hours 到相對應的 leave_times

**Comment by Maxwell-Alexius** [comment]
備註：不管是假單被取消或者是被駁回，都會將 locked_hours 回歸為 usable_hours

**Comment by Maxwell-Alexius** [comment]
備註：需要補上 Model Spec

**Comment by Eileen0917** [comment]
於 PR #115 中完成，且測試無誤，故關閉此 issue。
