### ISSUE TITLE
老闆權限 新增 "新增員工休假"

### ISSUE THREAD

**Issue by Eileen0917** [5xRuby/daikichi#81]
如wireframe中"新增員工休假"頁面，可讓老闆新增所有假別的員工休假額度。

**Comment by Maxwell-Alexius** [comment]
Manager & HR 類別可以新增

**Comment by Maxwell-Alexius** [comment]
新增員工休假，在 LeaveTime 的 Model 裡本身沒有存取 “原由”，故暫且以 simple_fields_for 方法代替

**Comment by YushengLi** [comment]
以 PR #79 中新增的 :remark 欄位作為 LeaveTime 新增的備註欄位。

**Comment by Eileen0917** [comment]
bug:
第二次再新增無效
剛新增完跳至"員工扣打"頁面時的"新增員工休假"無法使用

**Comment by YushengLi** [comment]
@Maxwell-Alexius 再麻煩修正了 🙇 

@Eileen0917 記得用 `@username` 的功能提醒相關的人喔 😄

**Comment by YushengLi** [comment]
另外 @Eileen0917 這個似乎跟 Issue #7 重複了？

**Comment by Eileen0917** [comment]
@Maxwell-Alexius  ＠YushengLi
不能用的有 " 公假 / sick1 / sick2 / funeral / 事假 "
其他假別就ok沒問題
另外我認為 " 曠職 " 不需要出現在新增員工休假的假別選項中？！

**Comment by YushengLi** [comment]
`曠職` 應該是不需要出現沒有錯，再麻煩檢查之後回報請 Maxwell 修正

**Comment by Eileen0917** [comment]
@Maxwell-Alexius 

- "員工休假扣打" 的 "切換休假種類至" 選項種類不對 ( 與 "新增員工休假" 中的 "假別" 無法對應的都會錯 )
- 新增員工休假 > 事假、婚假、公假、產假 -- 第二次再新增會跳錯誤訊息
- 新增員工休假 > 病假、喪假 -- 沒反應

**Comment by Maxwell-Alexius** [comment]
@Eileen0917  @YushengLi 
問題：
 - 曠職部分是需要被移除的嗎？ (目前我是把曠職在 `application.yml` 以及其 sample 檔註解掉)
 - 老闆新增病假部分是可以分別新增全薪跟半薪病假嗎？ （目前大概知道病假沒反應是因為沒有選到全薪或者半薪病假選項）

**Comment by Eileen0917** [comment]
在 PR #95 中完成，已檢查無誤。
