### ISSUE TITLE
調整假單與休假紀錄結構

### ISSUE THREAD

**Issue by YushengLi** [5xRuby/daikichi#82]
> :warning: 注意：此部分討論尚未決議是否採納。

據上週五的討論，為了讓填寫假單與請假額度的結算比較單純、清楚明瞭，討論將目前的結構修改成下面所述的可能性，在這邊做個紀錄：

## 修正原則
- 原假單新增 (LeaveApplication) 時直接綁定一筆額度 (LeaveTime) 並直接扣除可用額度 (Usable Hours)，假單拒絕 (Rejected) 或取消 (Canceled) 時才重新還回可用額度。這部分額度 (LeaveTime) 應該要將實際被使用的休假時數 (Used Hours)、跟尚未被核可的休假時數分開來。
- 假單 (LeaveApplication) 僅供員工提出休假申請用，不直接用來計算休假狀況，避免計算休假時數時造成錯亂。

## 修正方法
- 額度 (LeaveTime) 上面新增欄位紀錄尚未被核可的休假時數 (Locked Hours)，尚未被核可的休假時數紀錄於其中。
- 假單 (LeaveApplication) 歸假單，僅供員工申請休假時使用。
  - 請假時選擇休假類別 (Leave Type)，此休假類別與額度之類別不同。如：
    - 給薪事假
    - 無薪事假
    - 病假
    - 公假
    - 喪假 ... 等
  - 針對假單 (LeaveApplication) 所選之休假類別 (Leave Type)，鎖定對應的額度並生成休假紀錄。
    - 如：申請 8 小時給薪事假，將 4 小時補休、4 小時特休分別自可用額度扣除，轉為 Locked Hours。
    - 人資同意休假申請時，將 Locked Hours 轉為 Used Hours。
    - 諸如公假、喪假、婚嫁等發生時才有假的狀況，假單申請後、在人資核可前，導引人資順便開啟此類特別假的額度。

**Comment by YushengLi** [comment]
剛剛踩到的雷，休假額度 (LeaveTime) 範圍為動態，會造成假單產生後自動計算的困難。

**Comment by Eileen0917** [comment]
經昨日討論後目前可行作法如下：

1. 抓出所有可用額度。
2. 排序所有可用額度 ( 到期日 > 額度少 )。
3. 將請假時段細分為每小時，與可用額度做詳細比較。
4. 請假時段的每小時皆被劃掉 ( 都有對應到可用額度 ) ，此假單才成立。

**Comment by Eileen0917** [comment]
相關 issue #91 #92 #93 #94 皆完成，故關閉此 issue。
