### ISSUE TITLE
同時新增多人的休假額度

### ISSUE THREAD

**Issue by Maxwell-Alexius** [5xRuby/daikichi#83]
用個 form 可以一次直接新增多筆，按個 button 就帶入一樣的值（ 起迄區間 假種 時數 等等 )
( 像是有活動要給補休時可以直接一次搞定，不用一個人一個人去新增額度 )

**Comment by Eileen0917** [comment]
像有活動的話會給補休，
現在的話要管理員自己一個人一個人給額度，
期望可以也許是他整理好檔案：
```
user        leave_type     qouta       start date        expire date
A             bonus             8              2017/12/01    2018/03/31
.
.
.
```
按下匯入後就可以全部長完

**Comment by Eileen0917** [comment]
於 PR #253 中完成，故關閉此 issue。
