### ISSUE TITLE
針對假單 (LeaveApplication) 所選之休假類別 (Leave Type)，鎖定對應的額度並生成休假紀錄

### ISSUE THREAD

**Issue by Eileen0917** [5xRuby/daikichi#94]
據 issue #82 討論後結果：

將所請的假的額度自可用額度扣除，轉為 Locked Hours。
人資同意休假申請時，將 Locked Hours 轉為 Used Hours。
諸如公假、喪假、婚嫁等發生時才有假的狀況，假單申請後、在人資核可前，導引人資順便開啟此類特別假的額度。

**Comment by Eileen0917** [comment]
假單轉休假紀錄的驗證與做法：
排序所有可用額度 ( 以到期日為第一優先，再來是看額度較少的優先 )。並將請假時段以每日做細分，與可用額度做詳細比較，扣除可用額度，轉為鎖定額度。在請假時段全部都有對應到可用額度後，此假單才成立。

詳細流程：
1. 將 LeaveApplication 的開始日、結束日與每筆 LeaveTime 的期限開始日、到期日做比較，取較大(較晚開始)的開始時間為 base_start_time，較小(較早結束)的結束時間為 base_end_time。
2. 以 base_time 與 每筆 LeaveTime 做對應，將 base_time 的請假時數依序依照 LeaveTime 的 usable_hours 扣除，並將 usable_hours 轉為 locked_hours。
3. 若每筆 Date: hour 皆等於零，則假單成立，並產生對應的休假紀錄。但若比對完畢全部的 usable LeaveTime 後仍有不為零的 Date: hour，則拒絕假單生成。

**Comment by Maxwell-Alexius** [comment]
@YushengLi  @Eileen0917 
`model/leave_time.rb` 那邊的 `scope :overlaps` 目前測試過後好像不會包含 `beginning` 的日期，這個部分要修嗎？

例如：假設今天有  4/3 ~ 4/5 的假單要申請，然後 `available_leave_time` 有3筆：
```
1. #leave_time effective_date: 3/15, expiration_date: 4/15
2. #leave_time effective_date: 3/15, expiration_date: 4/3
 （只有覆蓋到4/3，也就是 leave_time的 beginning）
3. #leave_time effective_date: 4/5, expiration_date: 4/15
 （只有覆蓋到4/5，也就是 leave_time的 closing）
```

但 `available_leave_times` 出來的結果只有第一跟第三筆，所以 `overlaps` 沒有包含到 `beginning`

(我是有試過把 `leave_time` 的 `overlaps` 的 `beginning` 改成 `beginning: beginning - 1.day` 就可以包含起始日期，不過就要修一個 `spec`)

**Comment by YushengLi** [comment]
@Maxwell-Alexius 我剛剛看了一下應該是 Postgres 中 OVERLAPSE 對  DATE 計算上定義的問題。

> OVERLAPS automatically takes the earlier value of the pair as the start. Each time period is considered to represent the half-open interval start <= time < end, unless start and end are equal in which case it represents that single time instant.

Reference: [Postgres Date/Time Functions and Operators](https://www.postgresql.org/docs/current/static/functions-datetime.html)

這邊應該要做修正，可以改成用 `beginning_of_day`, `end_of_dat` timestamp 去做查詢，或是直接用單純的 `>=`, `<=` 運算符做查詢，直接將 `beginning - 1.day` 用來做查詢可能不太適合，這次修正應該一併連同 Spec 也修正，@Maxwell-Alexius 如果假單扣抵部分完成要不要連這邊一起處理？

**Comment by Maxwell-Alexius** [comment]
@Eileen0917 
我先貼在 `rails console` 的簡易使用方式：
先建立假單 `LeaveApplication`，然後建立假單的 quota => `LeaveTime` （我記得 `LeaveTime` 目前可以在前端那邊直接操作並建立出來，假單可能要自行在 console 產出）

假設我們要處理第一個 User 的第一張假單：

```
> u = User.first
> la = u.leave_applications.first
```

呼叫 `available_leave_times` 可以得到可以使用的 quota：

```
> la.available_leave_times
```

然後建立 `LeaveTimeUsageBuilder` 的 `instance` :

```
> ub = LeaveTimeUsageBuilder.new la
```

呼叫 `leave_hours_by_date` 方法即可得到分解假單過後，單位日期裡的時數：

```
> ub.leave_hours_by_date
```

使用 `build_leave_time_usages` 方法即可已自動判斷：
 - 假單之扣打要怎麼依序去扣 （由最早 expired 以及扣打少的開始扣起）
 - 如果還有缺少扣打可以去彌補假單時數則 `return false`
 - 除了建立出 `LeaveTimeUsage` 以外，會順便更新每張 `LeaveTime` 之 `locked_hours`
 - 若以上的動作皆正確 => `return true`

```
> ub.build_leave_time_usages
```

**Comment by Maxwell-Alexius** [comment]
@Eileen0917 
請測試 commit 9152041 的 LeaveTimeUsageBuilder 功能，這一次 LeaveApplication 起始時間也包含到 LeaveTime 上

**Comment by Eileen0917** [comment]
經測試確認可正確扣除假單所需額度，且依照額度扣除之先後順序。

**Comment by Eileen0917** [comment]
於 PR #113 中完成。
